package teclan.springboot.entity;

public class Users1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users1.id
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users1.name
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users1.age
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users1.id
     *
     * @return the value of users1.id
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users1.id
     *
     * @param id the value for users1.id
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users1.name
     *
     * @return the value of users1.name
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users1.name
     *
     * @param name the value for users1.name
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users1.age
     *
     * @return the value of users1.age
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users1.age
     *
     * @param age the value for users1.age
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}